import type { Bucket, EmailThread } from "./types";

export const DEFAULT_BUCKETS: Bucket[] = [
  {
    id: "important",
    name: "Important",
    description: "Time-sensitive requests, decisions, and direct obligations.",
    tone: "violet",
  },
  {
    id: "review",
    name: "Needs review",
    description: "Ambiguous or conflicting evidence that deserves a human look.",
    tone: "amber",
  },
  {
    id: "wait",
    name: "Can wait",
    description: "Useful information without an immediate action or deadline.",
    tone: "blue",
  },
  {
    id: "newsletter",
    name: "Newsletter",
    description: "Recurring editorial or marketing updates.",
    tone: "green",
  },
  {
    id: "archive",
    name: "Auto-archive",
    description: "Low-value automated mail. Recommendation only.",
    tone: "neutral",
  },
  {
    id: "escalations",
    name: "Customer escalations",
    description:
      "External customer blockers, outages, billing problems, or deadlines awaiting a response.",
    tone: "violet",
    custom: true,
  },
];

const common = {
  model: "kimi-k3",
  promptVersion: "triage-v4",
  taxonomyVersion: 2,
};

export const DEMO_THREADS: EmailThread[] = [
  {
    id: "t-001",
    sender: "Marcus Chen",
    email: "marcus@northstar.health",
    initials: "MC",
    avatarTone: "#f0eaff",
    subject: "URGENT: checkout failures since 2:10 PM",
    preview:
      "Payments are failing for every EU customer. We need an owner and ETA before our 4 PM status call.",
    time: "9:42",
    date: "Today, 9:42 AM",
    unread: true,
    starred: true,
    labels: ["External", "Customer"],
    status: "complete",
    participants: ["Marcus Chen", "Amogh Reddy", "Priya Shah"],
    messages: [
      {
        id: "m-001-a",
        sender: "Marcus Chen",
        email: "marcus@northstar.health",
        timestamp: "Today at 9:42 AM",
        content: [
          "Hi Amogh — payments are failing for every EU customer in the hosted checkout flow. We started seeing declines at 2:10 PM UTC and can reproduce it across three tenants.",
          "This is blocking today's launch. We need an owner and an ETA before our 4 PM status call. Can you confirm who is driving this?",
          "Thanks,\nMarcus\nVP Engineering, Northstar Health",
        ],
      },
    ],
    classification: {
      ...common,
      bucketId: "escalations",
      runnerUpBucketId: "important",
      rationale:
        "An external customer reports a live revenue blocker, asks for an owner, and gives a same-day deadline. The latest customer message is unanswered.",
      evidence: [
        "payments are failing for every EU customer",
        "This is blocking today's launch",
        "We need an owner and an ETA before our 4 PM status call",
      ],
      ambiguityReasons: [],
      needsReview: false,
      latencyMs: 812,
      costMicros: 1640,
    },
    groundTruth: "escalations",
  },
  {
    id: "t-002",
    sender: "Priya Shah",
    email: "priya@tenex.co",
    initials: "PS",
    avatarTone: "#e7f5ff",
    subject: "Contract renewal — final redlines due Thursday",
    preview:
      "Legal is aligned on everything except the liability cap. Can you sign off on the fallback position by 3 PM?",
    time: "9:18",
    date: "Today, 9:18 AM",
    unread: true,
    labels: ["Internal", "Legal"],
    status: "complete",
    participants: ["Priya Shah", "Amogh Reddy", "Legal"],
    messages: [
      {
        id: "m-002-a",
        sender: "Priya Shah",
        email: "priya@tenex.co",
        timestamp: "Today at 9:18 AM",
        content: [
          "Legal is aligned on everything except the liability cap. The customer will accept our fallback language if we confirm it today.",
          "Can you sign off on the fallback position by 3 PM? Final redlines are due Thursday morning.",
        ],
      },
    ],
    classification: {
      ...common,
      bucketId: "important",
      runnerUpBucketId: "wait",
      rationale:
        "The sender asks for a concrete decision with a same-day deadline, and the contract cannot advance without it.",
      evidence: [
        "Can you sign off on the fallback position by 3 PM?",
        "Final redlines are due Thursday morning",
      ],
      ambiguityReasons: [],
      needsReview: false,
      latencyMs: 641,
      costMicros: 1190,
    },
    groundTruth: "important",
  },
  {
    id: "t-003",
    sender: "Google Security",
    email: "no-reply@accounts.google.com",
    initials: "G",
    avatarTone: "#fff2dc",
    subject: "Security alert: unfamiliar sign-in detected",
    preview:
      "A new sign-in was detected on macOS. If this was you, no action is needed.",
    time: "8:56",
    date: "Today, 8:56 AM",
    unread: true,
    labels: ["Automated", "Security"],
    status: "review",
    participants: ["Google Security", "Amogh Reddy"],
    messages: [
      {
        id: "m-003-a",
        sender: "Google Security",
        email: "no-reply@accounts.google.com",
        timestamp: "Today at 8:56 AM",
        content: [
          "A new sign-in was detected on macOS near Austin, Texas.",
          "If this was you, no action is needed. If not, review your account activity immediately.",
        ],
      },
    ],
    classification: {
      ...common,
      bucketId: "review",
      runnerUpBucketId: "important",
      rationale:
        "The message could indicate account compromise, but the content alone cannot establish authenticity or whether the sign-in was expected.",
      evidence: [
        "A new sign-in was detected",
        "If not, review your account activity immediately",
      ],
      ambiguityReasons: [
        "Authenticity cannot be verified from message text",
        "The user's recent sign-in activity is unknown",
      ],
      needsReview: true,
      latencyMs: 923,
      costMicros: 1480,
    },
    groundTruth: "review",
  },
  {
    id: "t-004",
    sender: "Elena Garcia",
    email: "elena@tenex.co",
    initials: "EG",
    avatarTone: "#e7f8f0",
    subject: "Revised hiring plan for the board packet",
    preview:
      "Could you send the updated headcount assumptions before I lock the packet this afternoon?",
    time: "8:31",
    date: "Today, 8:31 AM",
    unread: false,
    labels: ["Internal", "Finance"],
    status: "complete",
    participants: ["Elena Garcia", "Amogh Reddy"],
    messages: [
      {
        id: "m-004-a",
        sender: "Elena Garcia",
        email: "elena@tenex.co",
        timestamp: "Today at 8:31 AM",
        content: [
          "The operating plan is almost final. I'm still using last week's engineering and GTM headcount assumptions.",
          "Could you send the updated numbers before I lock the board packet this afternoon?",
        ],
      },
    ],
    classification: {
      ...common,
      bucketId: "important",
      runnerUpBucketId: "wait",
      rationale:
        "A direct request is blocking a board deliverable due later today.",
      evidence: [
        "Could you send the updated numbers",
        "before I lock the board packet this afternoon",
      ],
      ambiguityReasons: [],
      needsReview: false,
      latencyMs: 598,
      costMicros: 1080,
    },
    groundTruth: "important",
  },
  {
    id: "t-005",
    sender: "Maya Brooks",
    email: "maya@acme.com",
    initials: "MB",
    avatarTone: "#fdebec",
    subject: "Re: launch timeline — does Friday still hold?",
    preview:
      "We have the enablement team scheduled. Please tell me today if we should move the customer announcement.",
    time: "Yesterday",
    date: "Yesterday, 4:12 PM",
    unread: false,
    labels: ["External", "Customer"],
    status: "review",
    participants: ["Maya Brooks", "Amogh Reddy", "Launch team"],
    messages: [
      {
        id: "m-005-a",
        sender: "Amogh Reddy",
        email: "amogh@tenex.co",
        timestamp: "Monday at 11:04 AM",
        content: [
          "Friday is still the target. I should have the final infrastructure sign-off tomorrow morning and will confirm then.",
        ],
      },
      {
        id: "m-005-b",
        sender: "Maya Brooks",
        email: "maya@acme.com",
        timestamp: "Yesterday at 4:12 PM",
        content: [
          "Checking back because we have the enablement team scheduled and still haven't seen the confirmation.",
          "Please tell me today if we should move the customer announcement.",
        ],
      },
    ],
    classification: {
      ...common,
      bucketId: "review",
      runnerUpBucketId: "escalations",
      rationale:
        "The customer is waiting on a promised confirmation and has a same-day planning need, but there is no explicit blocker or outage.",
      evidence: [
        "still haven't seen the confirmation",
        "Please tell me today if we should move the customer announcement",
      ],
      ambiguityReasons: [
        "Overlaps the custom escalation definition",
        "Customer impact is implied rather than explicit",
      ],
      needsReview: true,
      latencyMs: 1048,
      costMicros: 1910,
    },
    groundTruth: "escalations",
  },
  {
    id: "t-006",
    sender: "AWS Billing",
    email: "aws-billing@amazon.com",
    initials: "AWS",
    avatarTone: "#fff3e6",
    subject: "Your July cloud invoice is ready",
    preview:
      "Your monthly AWS invoice is now available. Total due: $4,218.16 on August 1.",
    time: "Yesterday",
    date: "Yesterday, 1:26 PM",
    unread: false,
    labels: ["Automated", "Billing"],
    status: "complete",
    participants: ["AWS Billing", "Amogh Reddy"],
    messages: [
      {
        id: "m-006-a",
        sender: "AWS Billing",
        email: "aws-billing@amazon.com",
        timestamp: "Yesterday at 1:26 PM",
        content: [
          "Your monthly AWS invoice is now available. Total due: $4,218.16 on August 1.",
          "You can review service-level detail in the Billing console. No action is required if automatic payment is enabled.",
        ],
      },
    ],
    classification: {
      ...common,
      bucketId: "wait",
      runnerUpBucketId: "archive",
      rationale:
        "This is a legitimate billing record with a future due date and no immediate action for accounts using automatic payment.",
      evidence: ["invoice is now available", "No action is required if automatic payment is enabled"],
      ambiguityReasons: [],
      needsReview: false,
      latencyMs: 522,
      costMicros: 850,
    },
    groundTruth: "wait",
  },
  {
    id: "t-007",
    sender: "Anika Rao",
    email: "anika@tenex.co",
    initials: "AR",
    avatarTone: "#eef0ff",
    subject: "FYI: Q3 roadmap notes",
    preview:
      "Sharing the cleaned-up notes from yesterday. No decisions needed before next Tuesday's planning session.",
    time: "Mon",
    date: "Monday, 5:04 PM",
    unread: false,
    labels: ["Internal", "Product"],
    status: "complete",
    participants: ["Anika Rao", "Product team", "Amogh Reddy"],
    messages: [
      {
        id: "m-007-a",
        sender: "Anika Rao",
        email: "anika@tenex.co",
        timestamp: "Monday at 5:04 PM",
        content: [
          "Sharing the cleaned-up notes from yesterday's Q3 roadmap review.",
          "No decisions are needed before next Tuesday's planning session. Add comments asynchronously if anything looks off.",
        ],
      },
    ],
    classification: {
      ...common,
      bucketId: "wait",
      runnerUpBucketId: "important",
      rationale:
        "The message is explicitly informational and says no decision is needed this week.",
      evidence: ["FYI", "No decisions are needed before next Tuesday"],
      ambiguityReasons: [],
      needsReview: false,
      latencyMs: 474,
      costMicros: 760,
    },
    groundTruth: "wait",
  },
  {
    id: "t-008",
    sender: "The Pragmatic Engineer",
    email: "newsletter@pragmaticengineer.com",
    initials: "PE",
    avatarTone: "#e6f7f3",
    subject: "The pulse: AI engineering teams in 2026",
    preview:
      "This week's subscriber edition covers model routing, evals, and why platform teams are changing shape.",
    time: "Mon",
    date: "Monday, 8:00 AM",
    unread: false,
    labels: ["Bulk", "Editorial"],
    status: "complete",
    participants: ["The Pragmatic Engineer", "Amogh Reddy"],
    messages: [
      {
        id: "m-008-a",
        sender: "The Pragmatic Engineer",
        email: "newsletter@pragmaticengineer.com",
        timestamp: "Monday at 8:00 AM",
        content: [
          "This week's subscriber edition covers model routing, evals, and why platform teams are changing shape.",
          "You are receiving this because you subscribed. Manage preferences or unsubscribe at any time.",
        ],
      },
    ],
    classification: {
      ...common,
      bucketId: "newsletter",
      runnerUpBucketId: "archive",
      rationale:
        "Recurring editorial content and explicit subscription language identify this as a newsletter.",
      evidence: ["This week's subscriber edition", "Manage preferences or unsubscribe"],
      ambiguityReasons: [],
      needsReview: false,
      latencyMs: 389,
      costMicros: 640,
    },
    groundTruth: "newsletter",
  },
  {
    id: "t-009",
    sender: "Statuspage",
    email: "noreply@statuspage.io",
    initials: "SP",
    avatarTone: "#eef1f3",
    subject: "Weekly uptime report: all systems operational",
    preview:
      "All monitored services met their SLOs. No incidents were recorded during the reporting period.",
    time: "Sun",
    date: "Sunday, 6:00 AM",
    unread: false,
    labels: ["Automated", "Report"],
    status: "complete",
    participants: ["Statuspage", "Amogh Reddy"],
    messages: [
      {
        id: "m-009-a",
        sender: "Statuspage",
        email: "noreply@statuspage.io",
        timestamp: "Sunday at 6:00 AM",
        content: [
          "All monitored services met their SLOs for the week of July 13–19.",
          "No incidents were recorded during the reporting period. This is an automated message.",
        ],
      },
    ],
    classification: {
      ...common,
      bucketId: "archive",
      runnerUpBucketId: "wait",
      rationale:
        "This routine automated report contains no incident, exception, request, or required action.",
      evidence: ["all systems operational", "No incidents were recorded", "automated message"],
      ambiguityReasons: [],
      needsReview: false,
      latencyMs: 431,
      costMicros: 690,
    },
    groundTruth: "archive",
  },
  {
    id: "t-010",
    sender: "GitHub",
    email: "noreply@github.com",
    initials: "GH",
    avatarTone: "#ececec",
    subject: "Dependabot updates for 14 repositories",
    preview:
      "Fourteen dependency pull requests were opened. None are marked as critical security updates.",
    time: "Sat",
    date: "Saturday, 2:14 AM",
    unread: false,
    labels: ["Automated", "Engineering"],
    status: "complete",
    participants: ["GitHub", "Amogh Reddy"],
    messages: [
      {
        id: "m-010-a",
        sender: "GitHub",
        email: "noreply@github.com",
        timestamp: "Saturday at 2:14 AM",
        content: [
          "Dependabot opened fourteen dependency update pull requests across repositories you watch.",
          "None are marked as critical security updates. Review them in your normal maintenance window.",
        ],
      },
    ],
    classification: {
      ...common,
      bucketId: "archive",
      runnerUpBucketId: "wait",
      rationale:
        "This is a routine automated digest with no critical alert or time-sensitive failure.",
      evidence: ["Dependabot", "None are marked as critical security updates"],
      ambiguityReasons: [],
      needsReview: false,
      latencyMs: 457,
      costMicros: 720,
    },
    groundTruth: "archive",
  },
  {
    id: "t-011",
    sender: "Field Notes",
    email: "hello@fieldnotes.design",
    initials: "FN",
    avatarTone: "#f7ece2",
    subject: "Last chance: save 40% on migration services",
    preview:
      "Our migration promotion ends tonight. Book a discovery call to lock in the discount.",
    time: "Fri",
    date: "Friday, 3:45 PM",
    unread: false,
    labels: ["Bulk", "Promotion"],
    status: "complete",
    participants: ["Field Notes", "Amogh Reddy"],
    messages: [
      {
        id: "m-011-a",
        sender: "Field Notes",
        email: "hello@fieldnotes.design",
        timestamp: "Friday at 3:45 PM",
        content: [
          "Our migration promotion ends tonight. Book a discovery call to lock in the 40% discount.",
          "You received this marketing email after downloading our guide. Unsubscribe here.",
        ],
      },
    ],
    classification: {
      ...common,
      bucketId: "archive",
      runnerUpBucketId: "newsletter",
      rationale:
        "Promotional bulk mail with an unsubscribe marker does not create a genuine user deadline.",
      evidence: ["40% discount", "marketing email", "Unsubscribe"],
      ambiguityReasons: [],
      needsReview: false,
      latencyMs: 376,
      costMicros: 610,
    },
    groundTruth: "archive",
  },
  {
    id: "t-012",
    sender: "Liam Walker",
    email: "liam@arcadia.vc",
    initials: "LW",
    avatarTone: "#eaf1ff",
    subject: "Intro to the Arcadia data team",
    preview:
      "Would Wednesday at 11 work for a short technical intro? Happy to send context first.",
    time: "Thu",
    date: "Thursday, 6:32 PM",
    unread: false,
    labels: ["External", "Meeting"],
    status: "complete",
    participants: ["Liam Walker", "Amogh Reddy"],
    messages: [
      {
        id: "m-012-a",
        sender: "Liam Walker",
        email: "liam@arcadia.vc",
        timestamp: "Thursday at 6:32 PM",
        content: [
          "The Arcadia data team would love to compare notes on agent evaluation infrastructure.",
          "Would Wednesday at 11 work for a short technical intro? Happy to send context first.",
        ],
      },
    ],
    classification: {
      ...common,
      bucketId: "important",
      runnerUpBucketId: "wait",
      rationale: "The sender asks a direct scheduling question that requires a reply.",
      evidence: ["Would Wednesday at 11 work"],
      ambiguityReasons: [],
      needsReview: false,
      latencyMs: 548,
      costMicros: 930,
    },
    groundTruth: "important",
  },
];

